backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "sections"
    label: "Seções"
    folder: "src/content/sections"
    create: true
    slug: "{{uuid}}"
    fields:
      - { label: "Tipo de Seção", name: "type", widget: "select", options: ["header", "text", "gallery", "map", "footer"] }
      - { label: "Conteúdo", name: "content", widget: "markdown" }
      - { label: "Imagens", name: "images", widget: "list", field: { label: "Imagem", name: "image", widget: "image" }, required: false }
      - { label: "Ordem", name: "order", widget: "number" }
