backend:
  name: github
  repo: thiagopaixao/teste_astro_stelvia
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "page"
    label: "Página"
    folder: "src/content/page"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - label: "Seções"
        name: "sections"
        widget: "list"
        types:
          - label: "Cabeçalho"
            name: "header"
            widget: "object"
            fields:
              - { label: "Imagem de Fundo", name: "backgroundImage", widget: "image" }
              - { label: "Título", name: "title", widget: "string" }
          - label: "Texto"
            name: "text"
            widget: "object"
            fields:
              - { label: "Conteúdo", name: "content", widget: "markdown" }
          - label: "Galeria"
            name: "gallery"
            widget: "object"
            fields:
              - label: "Imagens"
                name: "images"
                widget: "list"
                field: { label: "Imagem", name: "image", widget: "image" }
          - label: "Mapa"
            name: "map"
            widget: "map"
          - label: "Rodapé"
            name: "footer"
            widget: "object"
            fields:
              - { label: "Conteúdo", name: "content", widget: "markdown" }

custom_widgets:
  map: "src/admin/widgets/MapWidget.js"
